general:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  default_workspace:
    min_corner: [-1, -1, -1]
    max_corner: [1, 1, 1]
